# Generated by Django 3.0.3 on 2020-02-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierent',
            name='date_return',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movierent',
            name='date_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
