# Generated by Django 3.0.3 on 2020-02-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200225_1007'),
        ('location', '0002_auto_20200227_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierent',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_rent', to='movie.Movie'),
        ),
    ]
