# Generated by Django 3.0.3 on 2020-02-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_myprofile_favourite_snack'),
        ('location', '0004_auto_20200227_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierent',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_rent', to='client.MyProfile'),
        ),
    ]
