# Generated by Django 3.0.3 on 2020-02-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='favourite_snack',
        ),
    ]
