# Generated by Django 3.0.3 on 2020-03-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200302_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='label',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumb',
            field=models.ImageField(upload_to='media', verbose_name='affiche'),
        ),
    ]
